apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: demo-image-processor
  annotations:
    description: All-in-one demo
    wasmcloud.dev/authors: wasmCloud team
    wasmcloud.dev/source-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/rust/components/http-image-processor/wadm.yaml
    wasmcloud.dev/readme-md-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/rust/components/http-image-processor/README.md
    wasmcloud.dev/homepage: https://github.com/wasmCloud/wasmCloud/tree/main/examples/rust/components/http-image-processor
    wasmcloud.dev/categories: |
      http,http-server,rust,hello-world,example
spec:
  components:
    - name: image-analyzer
      type: component
      properties:
        image: file://./components/image-analyzer/build/image_analyzer.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1

        - type: link
          properties:
            target: httpclient
            namespace: wasi
            package: http
            interfaces: [outgoing-handler]

        - type: link
          properties:
            target: task-manager
            namespace: wasmcloud
            package: task-manager
            interfaces: [tracker]

    - name: image-processor
      type: component
      properties:
        image: file://./components/image-processor/build/image_processor.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1

        - type: link
          properties:
            target: blobstore
            namespace: wasi
            package: blobstore
            interfaces: [blobstore]

        - type: link
          properties:
            target: task-manager
            namespace: wasmcloud
            package: task-manager
            interfaces: [tracker]

    - name: task-manager
      type: component
      properties:
        image: file://./components/task-manager/build/task-manager.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1

        - type: link
          properties:
            target: postgres
            namespace: wasmcloud
            package: postgres
            interfaces: [query, prepared]
            target_config:
              - name: pg-task-db

    - name: http-router
      type: capability
      properties:
        image: file://./providers/http-router/build/http-router.par.gz
        config:
          - name: provider_config
            properties:
              port: "8080"
      traits:
        - type: link
          properties:
            target: task-manager
            namespace: wasmcloud
            package: task-manager
            interfaces: [tracker]

        - type: link
          properties:
            target: image-processor
            namespace: wasmcloud
            package: image-processor
            interfaces: [resizer]

        - type: link
          properties:
            target: blobstore
            namespace: wasi
            package: blobstore
            interfaces: [blobstore]

    - name: blobstore
      type: capability
      properties:
        image: ghcr.io/wasmcloud/blobstore-fs:0.8.0

    - name: postgres
      type: capability
      properties:
        image: ghcr.io/wasmcloud/sqldb-postgres:0.3.0
        config:
          - name: pg-task-db

    - name: httpclient
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-client:0.12.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
