apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secrets-vault.fullname" . }}
  labels:
    {{- include "secrets-vault.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "secrets-vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "secrets-vault.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "secrets-vault.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SV_VAULT_ADDRESS
            value: {{ .Values.config.vault.address }}
          - name: SV_VAULT_AUTH_METHOD
            value: {{ .Values.config.vault.auth_method_path }}
          - name: SV_JWT_AUTH_AUDIENCE
            value: {{ .Values.config.vault.jwt_auth_audience }}
          - name: SV_VAULT_DEFAULT_SECRET_ENGINE
            value: {{ .Values.config.vault.secret_engine_path }}
          - name: SV_SERVICE_NAME
            value: {{ .Values.config.service_name }}
          - name: SV_SECRETS_PREFIX
            value: {{ .Values.config.secrets_prefix }}
          - name: SV_SERVER_XKEY_SEED
            value: {{ .Values.config.xkey_seed }}
          - name: SV_SERVER_NKEY_SEED
            value: {{ .Values.config.nkey_seed }}
          - name: SV_JWKS_ADDRESS
            value: {{ .Values.config.jwks_address }}
          - name: SV_NATS_ADDRESS
            value: {{ .Values.config.nats.address }}
          ports:
            - name: jwks-endpoint
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
